### ISSUE TITLE
utils/utils.go 72 行 使用了错误的 地址数组

### ISSUE THREAD

**Issue by kscorl** [OpenIoTHub/aliddns#10]
应将
`Ipv6APIUrls = append(Ipv4APIUrls, config.ConfigModel.ApiUrl)`
改为
`Ipv6APIUrls = append(Ipv6APIUrls, config.ConfigModel.ApiUrl)`

**Comment by kscorl** [comment]
另外, 补充一下问题所在的 commitid: 39f0375b669b6730c9bec5796e0fcfcf897670de

**Comment by IoTServ** [comment]
> 39f0375

确实

**Comment by IoTServ** [comment]
那个Ubuntu snapcraft发布工具好像有问题，以后等他们修复了再发布新版本好了[github action](https://github.com/OpenIoTHub/aliddns/actions/runs/5429151491/jobs/9873961752#step:6:133)
