### ISSUE TITLE
获取ipv6地址时获取成了ipv4地址

### ISSUE THREAD

**Issue by Road-To-Gensokyo** [OpenIoTHub/aliddns#13]
![image](https://github.com/OpenIoTHub/aliddns/assets/24391614/fddce97f-4cf2-4fae-87b5-67069c622c38)

**Comment by IoTServ** [comment]
好的，我看看，我记得好像都失败了就变成ipv4地址替代，如果没有ipv6地址可以禁止ipv6同步

**Comment by Road-To-Gensokyo** [comment]
我这里电信回收了v4公网只能使用v6了，而且我确定我有v6 ip，在阿里云后台手动填写ip后是没问题的
![image](https://github.com/OpenIoTHub/aliddns/assets/24391614/aaf647c7-1086-4cac-b21f-4b6652334af2)
![image](https://github.com/OpenIoTHub/aliddns/assets/24391614/297b8f17-d8ea-430a-8308-89e5d4967815)

**Comment by IoTServ** [comment]
v0.0.20应该已经修复了，之前有人说过这个 #10 后来修复了，但是自动编译没有成功，我刚刚手动编译上传了，你下载v0.0.20试试

**Comment by IoTServ** [comment]
[自动编译的版本](https://github.com/OpenIoTHub/aliddns/actions/runs/6299150596/job/17099360759)已经编译成功了，v0.0.21，试一下哈，有问题随时提出

**Comment by Road-To-Gensokyo** [comment]
好的，更新之后确认已经修复v6解析，多谢
