### ISSUE TITLE
自己额外配置的apiUrl是放在列表最后的?

### ISSUE THREAD

**Issue by crt106** [OpenIoTHub/aliddns#14]
rt 在获取ipv6地址的时候 不知道为什么 var Ipv6APIUrls = []string{
	"http://v6.ipv6-test.com/api/myip.php",
	"http://bbs6.ustc.edu.cn/cgi-bin/myip",
	"http://ipv6.ident.me",
	"http://ipv6.icanhazip.com",
	"http://ipv6.yunohost.org",
} 这一批地址插查出来的都是指向路由器的地址(我路由器已经设置为ipv6 passthrough了) 目前只发现http://6.ipw.cn/这个是对的 想额外添加 但是又是放在最后的 还是以默认的那些为准

**Comment by IoTServ** [comment]
对的，现在默认是加最后面，[代码](https://github.com/OpenIoTHub/aliddns/blob/6325e7718b81d8ad37db9046fe1bbcb280f50e50/utils/utils.go#L72)

**Comment by IoTServ** [comment]
我可以发个新版本用户的放最前面

**Comment by IoTServ** [comment]
你可以试试[v0.0.22](https://github.com/OpenIoTHub/aliddns/releases/tag/v0.0.22),从这个版本开始是将用户自定义API加前面，如果留空字符串就不加，并且区分v4和v6的API

**Comment by crt106** [comment]
> 你可以试试[v0.0.22](https://github.com/OpenIoTHub/aliddns/releases/tag/v0.0.22),从这个版本开始是将用户自定义API加前面，如果留空字符串就不加，并且区分v4和v6的API

ok 已解决
