### ISSUE TITLE
About read me 

### ISSUE THREAD

**Issue by EE-zim** [OpenIoTHub/aliddns#4]
我通过snapcraft在我的树莓派上安装了该应用，并更新了配置文件。
关于配置文件中的更新时间和协议的配置似乎没有更多的解释。
我尝试在终端直接输入aliddns时，返回的结果时common not found。是不是该应用没有正确安装？我该怎么检查动态域名解析是否成功呢？

**Comment by IoTServ** [comment]
?

**Comment by EE-zim** [comment]
第一次用github issues，不太会用。=-=
