### ISSUE TITLE
get public ipv4 err

### ISSUE THREAD

**Issue by jeffreyhu3** [OpenIoTHub/aliddns#5]
I use snap version in my NAS server, the ddns work very well, but often get some err see below. These logs get from command "snap logs aliddns -f". Is there any way to change method get public IP such as replacement "http://members.3322.org/dyndns/getip"
```
2021-08-11T01:55:08Z aliddns.aliddns[18309]: 2021/08/11 09:55:08 get public ipv4 err：Get "http://members.3322.org/dyndns/getip": EOF
2021-08-11T01:55:38Z aliddns.aliddns[18309]: 2021/08/11 09:55:38 get public ipv4 err：Get "http://ifconfig.me/ip": dial tcp 34.117.59.81:80: i/o timeout
```

**Comment by IoTServ** [comment]
code here:
https://github.com/OpenIoTHub/aliddns/blob/37e4f959092b0c286019cab29ce36a0e434c6455/utils/utils.go#L18
https://github.com/OpenIoTHub/aliddns/blob/37e4f959092b0c286019cab29ce36a0e434c6455/utils/utils.go#L42
I will adjust the order and release a new version.
The same server may have different responses in different countries.

**Comment by jeffreyhu3** [comment]
Could you please add a custom configuration in aliddns.yaml for Ipv4APIUrls?  such as "http://whatismyip.akamai.com" is faster and stable compare with "http://members.3322.org/dyndns/getip"

**Comment by IoTServ** [comment]
> Could you please add a custom configuration in aliddns.yaml for Ipv4APIUrls? such as "http://whatismyip.akamai.com" is faster and stable compare with "http://members.3322.org/dyndns/getip"

https://github.com/OpenIoTHub/aliddns/blob/85bb15b52725543793b2e8e47ac0ab2f862279aa/utils/utils.go#L28
already in list

**Comment by IoTServ** [comment]
https://github.com/OpenIoTHub/aliddns/blob/a5840021428dead4fe253a66515e56ab839ad36d/utils/utils.go#L19
 "http://whatismyip.akamai.com" first now @v0.0.11
