### ISSUE TITLE
建议补充Protocol说明

### ISSUE THREAD

**Issue by fanxianluotuo** [OpenIoTHub/aliddns#6]
首先感谢作者，很好用。但是第一次使用的时候没反应，看日志发现因为没能获取ipv6就卡住了。看了一下代码加上-p ipv4或者改一下aliddns.yaml里的protocol参数就成功了，建议在readme里说明一下。就我这家用联通宽带来说好像去主动申请才会有ipv6。

**Comment by radarDeveloper** [comment]
好的，谢谢建议，我会处理一下

**Comment by IoTServ** [comment]
感谢你的反馈和肯定，你的建议很好，很快会有一个新版本来解决该问题
