### ISSUE TITLE
好像不能跟随系统重启而自动重启

### ISSUE THREAD

**Issue by jasonbohan** [OpenIoTHub/aliddns#8]
用docker 部署的，想使用--always=restart ，确保能跟随系统重启时一起启动，但提示不支持always 命令。
包括--name 命令来自定义容器名称也不可以。
请问开发者是否可以支持上述两个命令？谢谢

**Comment by IoTServ** [comment]
你那两个参数是传给docker的，跟我这个没关系

**Comment by jasonbohan** [comment]
那您怎么解决服务器意外重启后，你的容器不能自动重启的情况？

iotserv ***@***.***>于2022年4月21日 周四21:25写道：

**Comment by IoTServ** [comment]
iotserv@FarrydeMac-Pro pio % docker run --help

Usage:  docker run [OPTIONS] IMAGE [COMMAND] [ARG...]

所以你需要把--always=restart放镜像名称前面：
```sh
$ docker run --always=restart openiothub/aliddns:latest run -i myid -k mykey -m iothub.cloud -s www -c 60
```

**Comment by jasonbohan** [comment]
这样的话，容器起不来的

iotserv ***@***.***>于2022年4月21日 周四21:31写道：

**Comment by IoTServ** [comment]
$ docker run  --restart=always openiothub/aliddns:latest run -i myid -k mykey -m iothub.cloud -s www -c 60

**Comment by IoTServ** [comment]
你docker命令搞错了，参考https://www.cnblogs.com/humblexwang/p/15911727.html

**Comment by IoTServ** [comment]
没事就关了啊
